### ISSUE TITLE
5.9 error deleting user

### ISSUE THREAD

**Issue by carlock2022** [traccar/traccar-web#1181] opened 2023-09-24 02:12 UTC
Steps
1, install traccar 5.9 from 0 in linux
2. do not configure or modify anything, just register admin (in my tests admin user, admin password)
3.enter to traccar 
4. create a user 
6. delete the user and get this error,

pc, win10-win 11   brave and edge

![Captura de pantalla 2023-09-23 215949](https://github.com/traccar/traccar-web/assets/114795834/428a1b7a-e2d1-44fe-87ac-3834ebb5bedb)

**Comment by tananaev** [comment] 2023-09-24 02:14
Duplicate of https://github.com/traccar/traccar/issues/5183.

**Closed by tananaev** 2023-09-24 02:14 UTC

**Comment by carlock2022** [comment] 2023-09-24 02:38
Good afternoon, what would be the fixed version then since the error continues in another digital vps just installed the preview
![Uploading 1.jpg…]()

**Comment by tananaev** [comment] 2023-09-24 02:39
Next official release will include the fix.

**Comment by carlock2022** [comment] 2023-09-24 02:41
the preview either? I'm just asking to know when to try fixed
