### ISSUE TITLE
Posting geofense thru API not showing in the Traccar Web Geofense List.

### ISSUE THREAD

**Issue by yadhurajm** [traccar/traccar-web#778] opened 2020-07-23 13:15 UTC
Traccar Version 4.9
I am able to POST the geofence using API (POST Method in POSTMAN or Android Native app), the same geofence details I can able to get (using API GET Method), I even can see the records in Mysql DB.
But the geofence details not showing in the Web APP Geofense list which is created through API.

**Comment by tananaev** [comment] 2020-07-23 15:01
Dupe of forum post:

https://www.traccar.org/forums/topic/posting-geofense-thru-api-not-showing-in-the-traccar-web-geofense-list/

Please read contribution guidelines before posting here. GitHub is not for generic questions.

**Closed by tananaev** 2020-07-23 15:01 UTC
