### ISSUE TITLE
Login Popup Issue

### ISSUE THREAD

**Issue by kalp2525** [traccar/traccar-web#1090] opened 2023-03-23 12:39 UTC
**Describe the bug**
I implemented this traccar API in my website so there was one popup coming when I entered first time in browser.

**Expected behavior**
I expected remove popup which comes when I run web app first time.

**Screenshots**
This popup comes when start my web-app.
![image](https://user-images.githubusercontent.com/122508708/227205693-baf9287c-a5f6-4c3b-a12a-6248d0211742.png)

Here in API's there were session and server API called but there was token API status was pending.
![image](https://user-images.githubusercontent.com/122508708/227205752-100353ec-bf97-4941-9373-e0e27bda0888.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: All Browser

**Additional context**
When I give username and password and then press signin button on popup then traccar API working fine. But when I press cancel button of popup then token and all other API cancelled and HTTP 401 Unauthorized-WebApplicationException(SecurityRequestFilter: 126<...) this error gives by all the cancelled API's.

**Comment by tananaev** [comment] 2023-03-23 12:41
Duplicate of https://github.com/traccar/traccar-web/issues/1089.

**Closed by tananaev** 2023-03-23 12:41 UTC

**Comment by kalp2525** [comment] 2023-03-23 12:44
This bug comes in my website so which forum will I use for this issue?

**Comment by kalp2525** [comment] 2023-03-23 12:48
Thanks.
